/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dtk_Rec */

#ifndef _Included_com_dtk_Rec
#define _Included_com_dtk_Rec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dtk_Rec
 * Method:    RecImage
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dtk_Rec_RecImage
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
